version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Celebgram-SF-SDK"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pa8ajudgn2mh"
s3_prefix = "Celebgram-SF-SDK"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
